name: push
on:
  push:
    branches:
      - 'github-actions'
  schedule:
    - cron: '0 0 */1 * *'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: mowies/alpine-toolbox
          add_git_labels: true
          tags: latest
